### ISSUE TITLE
Load from string instead of path

### ISSUE THREAD

**Issue by JSLibBundles** [mkay581/resource-manager-js#3]
Hi, mkay581.  I have a particular need to load elements from strings instead of web server paths.  So I forked your repo in order to experiment with this.  Here's a sample of what I have in mind:

```JavaScript
    /**
     * Loads a javascript string.
     * @param {string|Array} scriptStrings - The literal text of one or more JavaScript scripts
     * @memberOf ResourceManager
     * @return {Promise} Returns a promise that resolves when all scripts have been loaded
     */
    loadScriptFromString (scriptStrings) {
        let script,
            map,
            loadPromises = [];
        scriptStrings = ensurePathArray(scriptStrings);
        scriptStrings.forEach(function (scriptString) {
            map = this._scriptMaps[scriptString] = this._scriptMaps[scriptString] || {};
            if (!map.promise) {
                map.scriptString = scriptString;
                map.promise = new Promise(function (resolve) {
                    script = this.createScriptElement();
                    script.setAttribute('type','text/javascript');
                    script.innerHTML = scriptString;
                    script.addEventListener('load', resolve);
                    this._head.appendChild(script);
                }.bind(this));
            }
            loadPromises.push(map.promise);
        }.bind(this));
        return Promise.all(loadPromises);
    }
```
General question: Do you think I'm on the right track with this? Is this how you would do it?

Specific question: I'm not too sure what this line of code does:
```JavaScript
map = this._scriptMaps[path] = this._scriptMaps[path] || {};
```
I don't recall ever seeing two equal signs in one line of JS.  Could you clue me in?
Thanks.

**Comment by mkay581** [comment]
Thanks for forking! I'm glad to see this is useful!

Hmm, interesting.. If you were thinking about adding this to the lib, I'm curious to know your use case that would require you to pass in JS code strings instead of placing the JS in different files to separate concerns. You mind elaborating on this?

`this._scriptMaps` is meant to be an object literal to cache all results (the values) to their paths (the keys), so that subsequent calls with the same `path` don't cause additional server requests, the same `script` tags won't be created, etc. but the cached result can be returned instead. In your case, you're just tacking your JS strings onto the keys of this object.

Also, two equal signs means you're declaring the value for two variables.

**Comment by JSLibBundles** [comment]
Thanks for your reply.  My use case is somewhat experimental and may not be viable at all.  

I'm working on an idea for web widgets that behave somewhat like traditional OOP objects throughout their life cycle.  Meaning that the widgets contain data as well as code.  The widgets could be stored in a NoSQL database such as MongoDb.  They would be presented using something like Vue.js to allow for real-time multi-user editing.  I would like for the web client to be agnostic about how the content makes it to the browser, but make sure that both code and data (i.e. the entire widget) uses the same delivery pipeline.

In this scenario the HTML+CSS+JavaScript content might come into the app as strings served from a database rather than as files served from HTTP.

The purpose of the experiment is to find out whether this makes sense at all.  Is a web browser so bound to HTTP that everything must come as a file served over HTTP, or can it use other ways to connect to content?  What if I want to create an Electron app that connects directly to a database server with no intervening HTTP server?  Would that work?  That's what I intend to find out.

**Comment by JSLibBundles** [comment]
> this._scriptMaps is meant to be an object literal ...

OK so it looks like you're using a map/dictionary like data structure where the keys are the URLs and the values are the DOM script elements, right?  That being the case, the latter part of the statement, 
```JavaScript
= this._scriptMaps[path] || {};
```
means "if this._scriptMaps[pat] already exists, assign that, otherwise assign a null object".  Do I have that right?

BTW, since my script strings will be much longer than typical URLs, I'll probably want to use a hash of the string as an index instead of the URL.

**Comment by mkay581** [comment]
Oh I see. Your project sounds interesting. 
Yes, your observations are correct. It would probably be more beneficial to use something other than the script string as an identifier, depending on how you're getting the script from the DB.

**Comment by mkay581** [comment]
@JSLibBundles going to close this for now. Hopefully I've answered all your questions. If you want to continue discussion, feel free to continue to respond here. :)
