### ISSUE TITLE
Sequential execution

### ISSUE THREAD

**Issue by mjdease** [mkay581/resource-manager-js#5]
It would be useful if scripts would be executed in the order they're specified in the array, not in the order they load. This would allow loading scripts that depend on other scripts. For example:

```js
// b.js depends on a.js
ResourceManager.loadScript(['a.js', 'b.js'])
```

**Comment by mkay581** [comment]
`loadScript()` returns a promise. So you should be able to do this with `async/await`

```js
async function loadAllScripts() {
    await ResourceManager.loadScript('a.js');
    // a.js loaded
    await ResourceManager.loadScript('b.js');
    // b.js loaded
}
```

**Comment by mjdease** [comment]
Yup that's how I'm handling it for now I was just thinking it would make sense if this was built into the API instead of requiring the abstraction to be built on top (perhaps behind an option given there's performance impact from now loading files sequentially)

**Comment by mkay581** [comment]
Yeah I see your point. You can just do

```js
async function loadAllScripts(scripts = []) {
    for (const script of scripts) {
        await ResourceManager.loadScript(script);
    }
}
```

This library was meant to be low-level which makes doing things like this pretty easy.

I'm just not sure if the above code is necessary to add to this library. I actually think adding something like this to the API might actually be a little more confusing when you have a case where some files need to be loaded sequentially and some don't. 

I'm not quite sure how you're using this lib, but another option is to just use `import` directly inside of `a.js` script file, which works in all modern browsers. It would eliminate having to use ResourceManager to load the `b.js` dependency for you.

```js
// inside of a.js
import  'b.js';
// b.js loaded
```

**Comment by mjdease** [comment]
Yeah I can understand the value in keeping the API simple 👍 

I'm loading in scripts I don't have direct control over so I can't `import` dependencies unfortunately.

Initially I was thinking loading could be done separate from execution ([it seems possible](http://www.phpied.com/preload-cssjavascript-without-execution/), if a bit hacky) so scripts would load in parallel and execute in sequence. Without the performance impact, this approach could be used without needing to change the public API.

**Comment by mkay581** [comment]
> I'm loading in scripts I don't have direct control over so I can't `import` dependencies unfortunately.

If the files themselves dont have their own dependencies specified, then why is a dependency tree necessary? 

Also, not certain of why loading a script but not executing it would be desirable, but there is [a proposal for dynamic loading](https://github.com/tc39/proposal-dynamic-import) which will allow you to load any file type (JS files included) at different points of execution.

Going to close this for now but feel free to continue the discussion.

**Comment by mjdease** [comment]
The dependency is that script `a.js` defines some global say `window.foo` and `b.js` requires `window.foo` to exist when it gets executed.

The idea behind not executing immediately is the resource manager could wait for all downloads to complete, and _then_ execute all in a guaranteed order. 

Dynamic imports are great, unfortunately IE11 support is a requirement in my case.

**Comment by mkay581** [comment]
If IE11 is a requirement, then why even use the library? :stuck_out_tongue: There is no expectation to have this library support IE11 in the future. What's the reason for not just doing this in your html file?

```html
<script src="path/to/a.js"></script>
<script src="path/to/b.js"></script>
```

**Comment by mjdease** [comment]
Ah, I didn't see that mentioned in the readme and hadn't gotten around to testing on IE yet, I'll find an alternate solution. 

The reason not to include it in the html file is I'm using code splitting to minimize initial load time and only one chunk needs these scripts (and the scripts are _very_ large) so I'm loading them only in that one chunk.
